[package]
name = "aoc24"
version = "0.1.20"
authors = ["John Greth <jgreth0@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
num-traits = "0.2.19"
rayon = "1.10.0"
scanf = "1.2.1"
