[package]
name = "aoc24"
version = "0.1.8"
authors = ["John Greth <jgreth0@gmail.com>"]
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
rayon = "1.10.0"
scanf = "1.2.1"
