name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_VERBOSE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace --all-targets --all-features
    - name: Run tests
      run: cargo test --workspace --all-targets --all-features
    - name: Lint
      run: cargo clippy --workspace --all-targets --all-features
    - name: Doc test
      run: cargo doc --workspace --all-features
    - name: Test doc test
      run: cargo test --doc --workspace --all-features
